### PR TITLE
Add the --nested-berksfiles option to `berks install`

### PR DESCRIPTION
**Pull request by ghost**
Hi Chris, thanks for your berkshelf_ext initiative! The `--nested-berksfiles` option is a life saver.  
My use case however is installing and vendorising cookbooks referred by a series of nested Berksfiles (think recursive librarian-chef), so I hacked in the option for the `install` subcommand.

### CODE REVIEW

**Comment by chrisroberts** [comment]
:+1: I'll get this merged into develop shortly. Thanks!

**Comment by chrisroberts** [comment]
Cherry picked into `develop`. Will be prepping up another release to get this out today. Thanks @vaskas!

**Comment by chrisroberts** [comment]
@vaskas this is out in the current release. and since you are in focusing around chef-solo, the [knife-bootstrapsync](https://github.com/heavywater/knife-bootstrapsync) plugin might be of interest in conjunction with this. Thanks!

**Comment by ghost** [comment]
@chrisroberts thanks for the pointer! Our workflow is actually based around https://github.com/locomote/gusteau.

**Pull request closed without merging**
